---
- name: Install python-apt - need move to deps or pre_tasks
  apt:
    name:
      - python-apt
    state: present

- name: get the rpm or apt package facts
  package_facts:
    manager: "apt"

- name: install docker
  become_user: root
  import_tasks: installation.yml
  when: (ansible_facts['packages']['docker-ce'] is undefined) or (ansible_facts['packages']['docker-ce'][0].version != docker_version)
